name = "burnmail-api"
compatibility_date = "2025-03-24"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "burnmail"
database_id = "10165c9d-6c91-41b0-9d8c-59b1cbfc20de"
migrations_dir = "drizzle/migrations"

[vars]
DOMAIN = "burnmail.dev"
PLAUSIBLE_DOMAIN = "https://s.lorenzo0111.me"

[triggers]
crons = ["0 0 * * *"]
